### PR TITLE
Added dependencies check

### PR DESCRIPTION
**Pull request by Nhoya**
Added checkdep function that check the existence of the dependencies listed inside the array, if all the dep are installed it continues the execution, otherwise it exit listing what is missing

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thabks for your pull request, @Nhoya! Please add some details to the OP so that @Feltzer can check it.

**Comment by Nhoya** [comment]
Done

**Comment by SecUpwN** [comment]
>Done

Thanks, please be patient until @Feltzer or @OlegSmelov confirmed your PR.

**Comment by Feltzer** [comment]
Looks good! Thanks for helping out!

**Pull request merged**
