### PR TITLE
1.0.14 compatibility without python dependency

### PR DESCRIPTION
**Pull request by itsamenathan**
Removed the dependency on python from @ysangkok and instead parsed dbus output with awk.

### CODE REVIEW

**Comment by ysangkok** [comment]
great, thanks for the port!

**Comment by SecUpwN** [comment]
Huge thanks for improving Spotify-AdKiller, @itsamenathan! :+1:

**Comment by cmt29** [comment]
No idea if this is related, but I'm seeing two Awk syntax errors if I load spotify-adkiller.sh manually:
`<awk: line 6: syntax error at or near ,
awk: line 16: syntax error at or near ,>`

And nothing appears in the DBUS_DEBUG: line when playing a Spotify track.

**Comment by SecUpwN** [comment]
@cmt29, please file a fresh Issue with the things you just listed. This allows better tracking.

**Pull request merged**
