### PR TITLE
WMTITLE updated

### PR DESCRIPTION
**Pull request by zsteinmetz**

### CODE REVIEW

**Comment by OlegSmelov** [comment]
Hmm... This would break compatibility with the old versions, so I don't think it's a good idea to merge. I think we need to try both and use the one that works.

Also, https://github.com/SecUpwN/Spotify-AdKiller/pull/22 should ideally be combined with this one.

@Feltzer, thoughts?

**Comment by zsteinmetz** [comment]
Yeah, you're right. It actually was a quick and dirty solution to bring back functionality. What about using regular expressions to just check whether there is a "Spotify" in the title?

**Comment by Feltzer** [comment]
I agree with @OlegSmelov. We have to make sure to remain backwards-compatible. RegEx would be the solution of choice. Alas, xprop `doesn't` support any type of RegEx. The best solution would likely be to use `xdotool` (which *does*  support RegEx) to get the window ID, but that would add another dependency.

For the time being I've put together another solution and pushed it to [a new branch](https://github.com/SecUpwN/Spotify-AdKiller/commit/1c205635a83193f45e1b8771a99168abaffa5cff). I don't think it's as elegant as it could be, but it does its job. I've added some documentation to the README to account for the changes.

Would love to hear your thoughts on this solution.

**Comment by SecUpwN** [comment]
Thanks for digging into it, @Feltzer. I know that haviing a separate branch might seem like the right thing for the time being, but I'd prefer our script to automatically handle this Issue, even if that means adding another dependency. We have listed the dependencies in our `README` and also added the correct commands to install all utilities and dependencies, so here is my feedback regarding this Issue:

1. Please merge the new `WmTitleDetection` branch into our `master` (Spotify will change it again)
2. Please delete the `WmTitleDetection` branch and update the commands in our `README`
3. Consider adding the `dns-block` branch into `master` - or has that already been done?

**Comment by Feltzer** [comment]
The changes in the testing branch don't require a new dependency, actually. I was talking in hypothetical terms. `xdotool` could provide a more elegant solution than the one in the `WmTitleDetection` branch, but would require another dependency. 

I think that the solution in the branch I linked to is sufficient for our needs, but I might have overlooked something, so I'd rather wait for some feedback from @OlegSmelov before committing it to the main branch. There might be a much better method out there that I haven't thought of, yet.

As far as the `dns-block` branch is concerned, I still have reservations against merging it with main. Not only because of the [ethical concerns discussed in the bug report](https://github.com/SecUpwN/Spotify-AdKiller/issues/15#issuecomment-52322934), but also because it seems to break some Spotify apps (e.g. Musixmatch). I think the [in-line documentation for `dns-block`](https://github.com/SecUpwN/Spotify-AdKiller/blob/master/spotify-wrapper.sh#L44-L55) is sufficient for the time being.

**Comment by OlegSmelov** [comment]
I think I've just realized something.

I booted up by Linux box I haven't been using for a long time. The title of Spotify's window has changed, even though I haven't updated the program. That probably means the title comes from Spotify's servers and not from the application itself.

If this is indeed the case, we can just update the title in the code as it was originally suggested by @zsteinmetz.

**Comment by SecUpwN** [comment]
>As far as the dns-block branch is concerned, I still have reservations against merging it with main.

Thanks for telling me your concerns, @Feltzer. I full agree with your reasoning!

>That probably means the title comes from Spotify's servers and not from the application itself.

Is there a way to dynamically fetch the title, @OlegSmelov? Otherwise we'd have to always change it..

**Comment by Feltzer** [comment]
>I booted up by Linux box I haven't been using for a long time. The title of Spotify's window has changed, even though I haven't updated the program. That probably means the title comes from Spotify's servers and not from the application itself.


Huh, you're right. I thought it had upgraded in the background, but looking through my `dpkg` logs I don't see any mention of an update.

>If this is indeed the case, we can just update the title in the code as it was originally suggested by @zsteinmetz.

Agreed.

> Is there a way to dynamically fetch the title, @OlegSmelov? Otherwise we'd have to always change it..

I don't think it would be worth the effort to devise something like this right now. I'd wager Spotify won't change the title for a few months.

I will do as @OlegSmelov suggested and merge the pull requests by @zsteinmetz. Thanks again for contributing!

**Pull request merged**
