### PR TITLE
Fix default config

### PR DESCRIPTION
**Pull request by datamaan**
See https://github.com/SecUpwN/Spotify-AdKiller/blob/master/spotify-adkiller.sh#L167

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks for the fix, @datamaan! Would you please clarify why this is currently wrong?

**Comment by datamaan** [comment]
Oh, sorry for being so brief. :-)

The default config currently says that the default mode is "continuous", but the code actually has "simple" as the default.
So one of the two should be fixed. I thought it would make more sense to correct the comment in the configs.

**Comment by SecUpwN** [comment]
Thanks for clarifying, @datamaan. Using `continuous` mode by default makes much more sense though since it prevents the awkward pause in between. Are you able to update your pull request to use that?

**Comment by datamaan** [comment]
I already deleted my fork. But I made a new one: #54

**Pull request closed without merging**
